name: DragonCraftLobby
version: ${project.version}-b${buildNumber}
main: pl.dcrft.DragonCraftLobby
api-version: 1.19
author: NickNickerYT
description: DragonCraftLobby
depend: [ AuthMe, PlaceholderAPI ]
commands:
  gracz:
    description: aa
  dcl:
    description: aa