package pl.dcrft.Managers.Statistic;

public enum StatisticType {
    SURVIVAL_KILLS,
    SURVIVAL_DEATHS,
    SURVIVAL_KDR,
    SURVIVAL_BLOCKS,
    SKYBLOCK_LEVEL,
    SKYBLOCK_MONEY,
    SURVIVAL_TIMEPLAYED,
    SURVIVAL_MARRY,


    SKYBLOCK_KILLS,
    SKYBLOCK_DEATHS,
    SKYBLOCK_KDR,
    SKYBLOCK_TIMEPLAYED,
    SKYBLOCK_MARRY,

    PVP_KILLS,
    PVP_DEATHS,
    PVP_ASSISTS,
    PVP_KDR,
    PVP_RANKING,
    PVP_LEVEL,
    PVP_KASA,
    PVP_KILLSTREAK,
    PVP_TIMEPLAYED,

    HNS_KILLS,
    HNS_DEATHS,
    HNS_KASA,
    HNS_TIMEPLAYED,


    RANK,
    SINCE,
    ONLINE
}
